### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by TyanColte** [rbsriobr/SBW#1]
I just acquired a SpaceBall 5000 serial and i'm not having any luck with this program. I'm using an RS-232 USB adapter and while I can connect to COM1 with this program and see it reading data in and writing data out. When i send it the string and try to hit buttons the button lights on the side and the axis reports do not show anything, everything is 0. Please help. I've followed the documentation to the letter and it's still not working.

**Comment by TyanColte** [comment]
Ended up buying a space navigator.

**Comment by RegJug** [comment]
I have to admit - I appreciate your thought and the work that went into
programming the gadget.

peas out
